export * from "./Home";
export * from "./Login";
export * from "./NotFound";
export * from "./SignUp";
export * from "./About";
export * from "./Contact";
export * from "./Products";
export * from "./ProductDetails";
export * from './Profile';